language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
- pip install -r requirements.txt
script:
- py.test
notifications:
  slack:
    secure: b15J17yGw2YourAqJDWVgEoQIM216X/kW2aMmaRkO0lJ9zkQ+0LV/3cJGKO8aYs96z5ZM+WV/hQNiyCNriwUUEi+d/XDzGpUcNiVSf5B+AOBkWqTkKmnkjrymUqGx9bLUtd6s7Vxj5A25xTQvFm0hgh0vyW8RMUiE6r3brEzA4gNhb25xDD7JwqHO/eOexPEITAQt6VHlrfChn5oFHn++GpwNjYU2qiSWAyiw/Et6W8S0IO2PTz+neognyRhdbOSm2ioEGetN2gDVfPKBb8/+yQafDdciQnU/zUmfb03lXvqPCyMP9+DNd8p+iSeeb3qjZP6YL5fp6lDD5Q0s5VVvrri/u6yViXEPMID7J+L+RLcnfkhCG+5x7scpDsjPINUamvcSuL8LHTV33AgHk8pAEEmdLLzbAEAm9Sc6nclsux2LOGRhyPVpkv0usk4QPerco1EshwnryxjbKrqFhWDVVL5mIOnMdL9/RnTdY/D35XBHeNE7f2SzNJAXg7SQ0Cd6YxKnFi46WMQOiBZkL2aI59+elKiw/AMXVLiuxdhGaDjA2ZP83swaLkvkUAuA57bHFS1pcaHFKoRxGG1jLk5RJF1QlnW5pbk9i5sFqO3Z+yKv57fU7S95cabLWKy2lWYMzDY4PYkXDF6Kzz1ZfQi6tvOS2pD+7/N6zlq9HfZM5w=
deploy:
  provider: pypi
  user: martintamare
  on:
    tags: true
  password:
    secure: qlwxO89T+BQKRuDA49gfZ8OhSJT53eFc+/GYhGqMnqJsFXAw1Boem6FMEaE4ZiBMk/DVjZGsszF6rvN7lYcD36ES7IvvMzr19AWpd7XexX6LggUFNdiUQTI9mILqv/pgBVLVROb56h9qAmP2cLbTVe9TIjPWXJ6y8jgHINojwOG/6b/Kcq6KhP0DHvz/HJG8uC+ombXuLYg4SHzuIldqk5tNIpCWQFvicPCp3zRr+oh30i6yy5/gEIRdVY9aiiNf3qarW/rsZZ5NTdAA1S0b9VptbTl6EJFcHcuZFAypoMWUPhSIYrqww8wreyK1AXM6MZ6Q2h6mecGGaO9E+M9+Z5iPAeA+C4BWX5gGatmetuUzvpWoRHgKwUkx8fjmaXnnPAhdAwVj/Gx32xHLp/2UGoiqAmYv2E5Oy8DadzyiS/4yiEWX1O1PB5OPvDZOvnDnk2szPcGRvIY86DL5w/DlPopl843hPusJ0MZHxC6uj/Loh6Okdt8dh1SZF6sS4//t+fICAcKxPBtb3CVjWpneRiEZnPPmvj5BWIEKaVWNWr8HBsBWfQW2vXpK32DgHCo1uFXvNSKTtj42YiWjB1c0Ok2YQi5fSLKS/8PrIZ3vdO3P4PvVw4gmG745VH0CirYHwJdLWHBns888Djwx/tTuEAIgdqZU+qo/+1sTeAC2i1U=
before_deploy: 'pip install -r requirements.txt'
