language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
- pip install -r requirements.txt
script:
- py.test
notifications:
  slack:
    secure: b15J17yGw2YourAqJDWVgEoQIM216X/kW2aMmaRkO0lJ9zkQ+0LV/3cJGKO8aYs96z5ZM+WV/hQNiyCNriwUUEi+d/XDzGpUcNiVSf5B+AOBkWqTkKmnkjrymUqGx9bLUtd6s7Vxj5A25xTQvFm0hgh0vyW8RMUiE6r3brEzA4gNhb25xDD7JwqHO/eOexPEITAQt6VHlrfChn5oFHn++GpwNjYU2qiSWAyiw/Et6W8S0IO2PTz+neognyRhdbOSm2ioEGetN2gDVfPKBb8/+yQafDdciQnU/zUmfb03lXvqPCyMP9+DNd8p+iSeeb3qjZP6YL5fp6lDD5Q0s5VVvrri/u6yViXEPMID7J+L+RLcnfkhCG+5x7scpDsjPINUamvcSuL8LHTV33AgHk8pAEEmdLLzbAEAm9Sc6nclsux2LOGRhyPVpkv0usk4QPerco1EshwnryxjbKrqFhWDVVL5mIOnMdL9/RnTdY/D35XBHeNE7f2SzNJAXg7SQ0Cd6YxKnFi46WMQOiBZkL2aI59+elKiw/AMXVLiuxdhGaDjA2ZP83swaLkvkUAuA57bHFS1pcaHFKoRxGG1jLk5RJF1QlnW5pbk9i5sFqO3Z+yKv57fU7S95cabLWKy2lWYMzDY4PYkXDF6Kzz1ZfQi6tvOS2pD+7/N6zlq9HfZM5w=
